### ISSUE TITLE
Error: cannot call methods on igGrid prior to initialization; attempted to call method 'destroy'

### ISSUE THREAD

**Issue by shankar1414k** [IgniteUI/igniteui-angularjs#111]
Hi 
when I try to bind columns and rows dynamically  using igGrid in angular 2, it is throwing the below error

 Error: cannot call methods on igGrid prior to initialization; attempted to call method 'destroy'
    at Function.error (http://code.jquery.com/jquery-1.9.1.min.js:3:4022)
    at HTMLTableElement.<anonymous> (http://code.jquery.com/ui/1.10.3/jquery-ui.min.js:5:6122)
    at Function.each (http://code.jquery.com/jquery-1.9.1.min.js:3:5257)
    at init.each (http://code.jquery.com/jquery-1.9.1.min.js:3:2013)
    at init.t.fn.(anonymous function) [as igGrid] (http://code.jquery.com/ui/1.10.3/jquery-ui.min.js:5:5897)
    at IgGridComponent.set [as options] (http://10.162.85.116/vendor.bundle.js:113215:51)
    at updateProp (http://10.162.85.116/vendor.bundle.js:11383:37)
    at checkAndUpdateDirectiveInline (http://10.162.85.116/vendor.bundle.js:11084:19)
    at checkAndUpdateNodeInline (http://10.162.85.116/vendor.bundle.js:12501:17)
    at checkAndUpdateNode (http://10.162.85.116/vendor.bundle.js:12469:16)
    at prodCheckAndUpdateNode (http://10.162.85.116/vendor.bundle.js:12922:5)

usage inside typescript:
this.id = 'grid1';
    this.gridOptions = {
            width: '100%',
            columns:this.columns,
            dataSource: this.rows,
            autofitLastColumn: false,
            autoGenerateColumns: false,
            
        };
usage inside HTML : <ig-grid [(options)]='gridOptions' [(widgetId)]='id'></ig-grid>
   
Please help

**Comment by kdinev** [comment]
Seems like this is an issue for the `igniteui-angular-wrappers` repository, and it should no longer be reproducible.
